import 'dart:io';

import 'package:path/path.dart' as p;

import '../constants/files.dart';

bool routesDirExists() {
  final path = p.absolute(routesDir);
  return Directory(path).existsSync();
}

bool routeAppFileExists() {
  final path = p.absolute(routeOutputPath);
  return File(path).existsSync();
}

void initRouteAppFile([bool addIndexPage = false]) {
  final appPath = p.absolute(routeOutputPath);
  final appFile = File(appPath);
  appFile.createSync(recursive: true);
  appFile.writeAsStringSync('''
/// THIS IS AUTO-GENERATED BY BEATX CLI. DO NOT MODIFY THIS FILE.

final \$appRoutes = [
];
''');
}

void initRoutesDir() {
  final indexPagePath = p.normalize('$routesDir/index.dart');
  final indexPageFile = File(indexPagePath)..createSync(recursive: true);
  indexPageFile.writeAsStringSync('''
import 'package:flutter/material.dart';
import 'package:beatx/beatx.dart';

@XRoute()
class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text('Hello World!'),
      ),
    );
  }
}
''');
  initRouteAppFile(true);
}
