/// AUTO GENERATED BY BEATX
/// DO NOT MODIFY THIS BY YOURSELF
import 'package:flutter/widgets.dart';
import 'package:go_router/go_router.dart';

import r'details.$id.dart';

GoRoute get $detailsScreenRoute => GoRouteData.$route(
      path: '/details/:id',
      factory: DetailsScreenRoute.fromState,
    );

class DetailsScreenRoute extends GoRouteData {
  const DetailsScreenRoute();

  factory DetailsScreenRoute.fromState(GoRouterState state) {
    return const DetailsScreenRoute();
  }

  @override
  Widget build(BuildContext context) => const DetailsScreen();

  String get location => GoRouteData.$location(
        '/details/:id',
        queryParams: {},
      );

  void go(BuildContext context) => context.go(location, extra: this);

  void push(BuildContext context) => context.push(location, extra: this);

  void replace(BuildContext context) => context.replace(location, extra: this);
}
