/// AUTO GENERATED BY BEATX
/// DO NOT MODIFY THIS BY YOURSELF
import 'package:flutter/widgets.dart';
import 'package:go_router/go_router.dart';

import r'index.dart';

GoRoute get $mainScreenRoute => GoRouteData.$route(
      path: '/',
      factory: MainScreenRoute.fromState,
    );

class MainScreenRoute extends GoRouteData {
  const MainScreenRoute(this.title, {required this.$extra});

  factory MainScreenRoute.fromState(GoRouterState state) {
    final title = state.queryParams['title']!;
    final $extra = state.extra as int;

    return MainScreenRoute(title, $extra: $extra);
  }

  final String title;
  final int $extra;

  @override
  Widget build(BuildContext context) => MainScreen(title, $extra: $extra);

  String get location => GoRouteData.$location(
        '/',
        queryParams: {if (title != null) 'title': title},
      );

  void go(BuildContext context) => context.go(location, extra: this);

  void push(BuildContext context) => context.push(location, extra: this);

  void replace(BuildContext context) => context.replace(location, extra: this);
}
