/// AUTO GENERATED BY BEATX
/// DO NOT MODIFY THIS BY YOURSELF

import 'package:flutter/widgets.dart';
import 'package:go_router/go_router.dart';
import r'mypage.alarms.dart';

GoRoute get $alarmsSettingsRoute => GoRouteData.$route(
      path: '/mypage/alarms',
      factory: AlarmsSettingsRoute.fromState,
    );

class AlarmsSettingsRoute extends GoRouteData {
  const AlarmsSettingsRoute();

  factory AlarmsSettingsRoute.fromState(GoRouterState state) {
    return AlarmsSettingsRoute();
  }

  @override
  Widget build(BuildContext context) => AlarmsSettings();

  String get location => GoRouteData.$location(
        '/mypage/alarms',
        queryParams: {},
      );

  void go(BuildContext context) => context.go(location, extra: this);

  void push(BuildContext context) => context.push(location, extra: this);

  void replace(BuildContext context) => context.replace(location, extra: this);
}
