# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: VGVentures/very-good-coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 95
          exclude: "**/*_observer.dart **/change.dart"
